# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # ensure only one action runs at a time
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install texlive-full dvisvgm inkscape cmark-gfm

      - name: Checkout incunable
        uses: actions/checkout@v4
        with:
          repository: sjoblomj/incunable
          path: incunable

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: thi

      - name: Build static website
        run: |
          cd incunable
          ./html/compile.sh ../thi/content thi_output ../thi/resources ../thi/templates
          cd ..
          cp -r incunable/thi_output thi/public

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        working-directory: thi
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
